### ISSUE TITLE
Various Maven Warnings impacting Maven 4+

### ISSUE THREAD

**Issue by yeikel** [reactiverse/vertx-maven-plugin#480] opened 2023-05-18 16:57 UTC
> * io.reactiverse:vertx-maven-plugin:1.0.28
> [WARNING]   Declared at location(s):
> [WARNING]    * sample:0.0.0-SNAPSHOT (pom.xml) @ line 146
> [WARNING]   Used in module(s):
> [WARNING]    * sample:0.0.0-SNAPSHOT (pom.xml)
> [WARNING]   Plugin issue(s):
> [WARNING]    * Plugin mixes multiple Maven versions: [3.8.5, 3.3.9]
> [WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-artifact:3.8.5, org.apache.maven:maven-repository-metadata:3.8.5, org.apache.maven:maven-aether-provider:3.3.9, org.apache.maven:maven-model-builder:3.8.5, org.apache.maven:maven-plugin-api:3.8.5, org.apache.maven:maven-model:3.8.5, org.apache.maven:maven-builder-support:3.8.5]
> [WARNING]    * Plugin depends on plexus-container-default, which is EOL
> [WARNING]   Mojo issue(s):
> [WARNING]    * Mojo vertx:initialize (io.reactiverse.vertx.maven.plugin.mojos.InitializeMojo)
> [WARNING]      - Implements `Contextualizable` interface from Plexus Container, which is EOL.
> [WARNING]    * Mojo vertx:package (io.reactiverse.vertx.maven.plugin.mojos.PackageMojo)
> [WARNING]      - Implements `Contextualizable` interface from Plexus Container, which is EOL.

Reproduce this running : 

`mvn clean verify -Dmaven.plugin.validation=verbose`

**Comment by tsegismont** [comment] 2023-05-22 08:10
Thank you for reporting this

**Comment by tsegismont** [comment] 2024-06-19 13:59
Probably fixed by #587 (cannot reproduce)

**Closed by tsegismont** 2024-06-19 13:59 UTC
Labels: bug
